language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - '10'
  - '11'
script:
  - yarn test:prod && yarn build
after_success:
  - yarn travis-deploy-once "yarn report-coverage"
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
